# version: "3.8"
# services:
#   web:
#     build: .
#     ports:
#       - "80:80"
#     environment:
#       - DATABASE_URL=postgresql+psycopg2://hamroh_user:hamroh@db:5432/hamroh_db
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: hamroh_user  
#       POSTGRES_PASSWORD: hamroh  
#       POSTGRES_DB: hamroh_db     
#     volumes:
#       - postgres_data:/var/lib/postgresql/data 

# volumes:
#   postgres_data:
#     driver: local
